export const genres = [
  { id: 1, genre: "Action" },
  { id: 2, genre: "Adult" },
  { id: 3, genre: "Adventure" },
  { id: 4, genre: "Animation" },
  { id: 5, genre: "Biographical" },
  { id: 6, genre: "Comedy" },
  { id: 7, genre: "Crime" },
  { id: 8, genre: "Drama" },
  { id: 9, genre: "Fantasy" },
  { id: 10, genre: "Fiction" },
  { id: 11, genre: "Gangster" },
  { id: 12, genre: "Historical film" },
  { id: 13, genre: "Horror" },
  { id: 14, genre: "Martial Arts" },
  { id: 15, genre: "Monster" },
  { id: 16, genre: "Music" },
  { id: 17, genre: "Mystery" },
  { id: 18, genre: "Romance" },
  { id: 19, genre: "Romantic comedy" },
  { id: 20, genre: "Science" },
  { id: 21, genre: "Science fiction" },
  { id: 22, genre: "Sports" },
  { id: 23, genre: "Spy" },
  { id: 24, genre: "Superhero" },
  { id: 25, genre: "Teen" },
  { id: 26, genre: "Thriller" },
  { id: 27, genre: "War" },
  { id: 28, genre: "Western" },
];
